-- =====================================================
-- Łukaszek become Analyst
-- Day 64–65
-- Customer analytics and RFM segmentation
-- =====================================================



-- =====================================================
-- SECTION 1
-- Create a sample transactions table
-- This dataset is used for customer revenue analysis
-- and RFM segmentation
-- =====================================================

-- Drop the table if it already exists
-- This makes the script re-runnable

DROP TABLE IF EXISTS transactions;


-- Create the transactions table
-- Each row represents one customer transaction

CREATE TABLE transactions (
    transaction_id INT PRIMARY KEY,
    customer_id INT,
    transaction_date DATE,
    amount NUMERIC(10,2)
);


-- Insert sample data
-- The dataset contains 30 transactions
-- for 10 customers

INSERT INTO transactions (transaction_id, customer_id, transaction_date, amount) VALUES
(1, 1, '2025-01-10', 120.00),
(2, 1, '2025-02-15', 200.00),
(3, 1, '2025-04-20', 350.00),

(4, 2, '2025-01-05', 50.00),
(5, 2, '2025-03-12', 75.00),
(6, 2, '2025-06-10', 100.00),

(7, 3, '2025-02-01', 500.00),
(8, 3, '2025-03-01', 450.00),
(9, 3, '2025-04-01', 700.00),

(10, 4, '2025-01-25', 30.00),
(11, 4, '2025-02-18', 45.00),
(12, 4, '2025-05-11', 60.00),

(13, 5, '2025-02-14', 900.00),
(14, 5, '2025-03-20', 1100.00),
(15, 5, '2025-04-25', 1200.00),

(16, 6, '2025-01-07', 80.00),
(17, 6, '2025-02-07', 90.00),
(18, 6, '2025-03-07', 100.00),

(19, 7, '2025-02-21', 300.00),
(20, 7, '2025-04-10', 350.00),
(21, 7, '2025-06-12', 400.00),

(22, 8, '2025-01-15', 40.00),
(23, 8, '2025-02-20', 50.00),
(24, 8, '2025-03-22', 60.00),

(25, 9, '2025-04-01', 700.00),
(26, 9, '2025-05-01', 800.00),
(27, 9, '2025-06-01', 900.00),

(28, 10, '2025-01-10', 150.00),
(29, 10, '2025-03-10', 200.00),
(30, 10, '2025-06-10', 250.00);



-- =====================================================
-- DAY 64
-- Identify top customers based on revenue
-- and number of transactions
-- =====================================================

-- Step 1
-- Identify the last transaction for each customer
-- ROW_NUMBER is used to sort transactions
-- from the newest to the oldest one

WITH last_transaction AS (

    SELECT
        customer_id,
        transaction_date AS last_transaction_date,
        amount AS last_transaction_amount
    FROM (

        SELECT
            customer_id,
            transaction_date,
            amount,

            ROW_NUMBER() OVER (
                PARTITION BY customer_id
                ORDER BY transaction_date DESC, transaction_id DESC
            ) AS rn

        FROM transactions

    ) t

    WHERE rn = 1
),


-- Step 2
-- Count the number of transactions for each customer

transaction_count AS (

    SELECT
        customer_id,
        COUNT(*) AS transactions_cnt

    FROM transactions
    GROUP BY customer_id
),


-- Step 3
-- Calculate total revenue generated by each customer

customer_revenue AS (

    SELECT
        customer_id,
        SUM(amount) AS total_revenue

    FROM transactions
    GROUP BY customer_id
),


-- Step 4
-- Rank customers by total revenue
-- If revenue is the same, use the number of transactions
-- as a tie-breaker

rank_metric AS (

    SELECT
        lt.customer_id,
        tc.transactions_cnt,
        cr.total_revenue,

        DENSE_RANK() OVER (
            ORDER BY cr.total_revenue DESC,
                     tc.transactions_cnt DESC
        ) AS revenue_transactions_rank

    FROM last_transaction lt
    JOIN transaction_count tc
        ON lt.customer_id = tc.customer_id
    JOIN customer_revenue cr
        ON lt.customer_id = cr.customer_id
)


-- Step 5
-- Return top 5 customers

SELECT
    customer_id,
    transactions_cnt,
    total_revenue,
    revenue_transactions_rank

FROM rank_metric

ORDER BY revenue_transactions_rank
LIMIT 5;



-- =====================================================
-- DAY 64
-- Pareto revenue analysis
-- Check how much revenue is generated
-- by the top 10 customers
-- =====================================================

-- Step 1
-- Calculate total revenue for each customer
-- and rank customers from highest to lowest revenue

WITH customer_metric AS (

    SELECT
        customer_id,
        SUM(amount) AS customer_revenue,

        RANK() OVER (
            ORDER BY SUM(amount) DESC
        ) AS revenue_rank

    FROM transactions
    GROUP BY customer_id
),


-- Step 2
-- Calculate:
-- 1. total revenue across all customers
-- 2. revenue generated by top 10 customers

revenue_metric AS (

    SELECT
        customer_id,
        customer_revenue,
        revenue_rank,

        SUM(customer_revenue) OVER () AS total_revenue,

        SUM(customer_revenue)
            FILTER (WHERE revenue_rank <= 10) OVER () AS top10_revenue

    FROM customer_metric
)


-- Step 3
-- Calculate percentage share of top 10 customers
-- in total revenue

SELECT
    ROUND(
        100.0 * top10_revenue / NULLIF(total_revenue, 0),
        2
    ) AS top10_revenue_percentage

FROM revenue_metric

LIMIT 1;



-- =====================================================
-- DAY 65
-- RFM analysis
-- Segment customers by:
-- Recency    = how recently the customer purchased
-- Frequency  = how often the customer purchased
-- Monetary   = how much the customer spent
-- =====================================================

-- Step 1
-- Calculate the number of transactions for each customer

WITH count_metric AS (

    SELECT
        customer_id,
        COUNT(*) AS frequency

    FROM transactions
    GROUP BY customer_id
),


-- Step 2
-- Calculate total spending for each customer

total_revenue_metric AS (

    SELECT
        customer_id,
        SUM(amount) AS monetary

    FROM transactions
    GROUP BY customer_id
),


-- Step 3
-- Find the most recent transaction date for each customer

last_date_metric AS (

    SELECT
        customer_id,
        MAX(transaction_date) AS last_transaction_customer_date

    FROM transactions
    GROUP BY customer_id
),


-- Step 4
-- Combine all metrics in one result
-- and assign RFM scores from 1 to 5

final_metric AS (

    SELECT
        l.customer_id,

        CURRENT_DATE - l.last_transaction_customer_date AS recency_days,
        c.frequency,
        t.monetary,

        -- Recency score:
        -- lower recency_days means more recent activity,
        -- so more recent customers should receive higher scores

        NTILE(5) OVER (
            ORDER BY CURRENT_DATE - l.last_transaction_customer_date DESC
        ) AS r_score,

        -- Frequency score:
        -- customers with more transactions receive higher scores

        NTILE(5) OVER (
            ORDER BY c.frequency
        ) AS f_score,

        -- Monetary score:
        -- customers with higher spending receive higher scores

        NTILE(5) OVER (
            ORDER BY t.monetary
        ) AS m_score

    FROM last_date_metric l
    JOIN count_metric c USING(customer_id)
    JOIN total_revenue_metric t USING(customer_id)
),


-- Step 5
-- Create an RFM segment code
-- and assign a descriptive segment label

segment_metric AS (

    SELECT
        customer_id,
        recency_days,
        frequency,
        monetary,
        r_score,
        f_score,
        m_score,

        CONCAT(r_score, f_score, m_score) AS rfm_segment,

        CASE
            WHEN CONCAT(r_score, f_score, m_score) = '555'
                THEN 'best customers'
            WHEN CONCAT(r_score, f_score, m_score) = '155'
                THEN 'new high value'
            WHEN CONCAT(r_score, f_score, m_score) = '511'
                THEN 'loyal low spend'
            WHEN CONCAT(r_score, f_score, m_score) = '111'
                THEN 'lost customers'
            ELSE 'other'
        END AS segment_name

    FROM final_metric
)


-- Step 6
-- Count how many customers belong to each segment

SELECT
    rfm_segment,
    segment_name,
    COUNT(*) AS number_of_customers

FROM segment_metric

GROUP BY
    rfm_segment,
    segment_name

ORDER BY
    number_of_customers DESC,
    rfm_segment;
